### PR TITLE
Documentparsing

### PR DESCRIPTION
**Pull request by CosmicWebServices**
### What issue(s) does this fix?
#36 

### Is this complete or a WIP?

Complete

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
I'll fix it after school...

**Comment by CosmicWebServices** [comment]
Fixed!

**Review by joker314 — CHANGES_REQUESTED** [review]
The file should be closed after being read.

**Comment by CosmicWebServices** [comment]
@joker314 thanks! Fixing now

**Comment by CosmicWebServices** [comment]
@joker314 Fixed the suggestion

**Review by joker314 — APPROVED** [review]
Lovely

**Comment by joker314** [comment]
Happy to merge or do we need everybody to review it?

**Comment by CosmicWebServices** [comment]
Nope, just one!

**Pull request merged**
