### PR TITLE
More background colors

### PR DESCRIPTION
**Pull request by rogersouza**
### What issue(s) does this fix?

#25

### Is this complete or a WIP?

*Complete*

### Other

*Let me know if you don't like the variables name or if there's something wrong. Thanks :)*

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
@rogersec Thanks for the pr... sadly there seems to be conflicts. Could you fix them and add the new colors to the readme.md chart? Thanks again!

**Comment by rogersouza** [comment]
Oh, sorry about that. i'll fix it right now

**Comment by CosmicWebServices** [comment]
No problem at all :D I can reopen the issue if you want me to...

**Comment by CosmicWebServices** [comment]
Are you working on updating the docs if not I have some time to do it myself :D Thanks again! 👍

**Comment by rogersouza** [comment]
I'm working on it :)

**Comment by rogersouza** [comment]
I'm supposed to add all the new properties on the readme.md?

**Comment by CosmicWebServices** [comment]
You're awesome!

Yep! Hopefully, the chart makes sense if not I can explain it... Maybe you should add a new light background row.

**Comment by rogersouza** [comment]
One more thing: 
Do you think we should change the name of the variables like 'red_bg' to 'dark_red_bg', for example? So we will have light_red_bg and dark_red_bg

**Comment by CosmicWebServices** [comment]
I think they are fine for now

**Comment by rogersouza** [comment]
Am i forgetting something?

**Comment by CosmicWebServices** [comment]
About to merge! Just got to wait till travis checks out

**Pull request merged**
