### PR TITLE
Some different background colors

### PR DESCRIPTION
**Pull request by rogersouza**
Hello!
I added some properties to the 'codes dict' that change the background colors. The colors are:
    -Black
    -Red
    -Green
    -Brown
    -Blue
    -Purple
    -Cyan
    -Gray

Let me know if there's any error.

*This is my first contribution to an open source project, so please be kind and forgive me in case of mistakes

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
Thanks for your contribution!

This is a great addition I just want to make sure that the variable names you are using are suitable.

@joker314 and/or @TheMonsterFromTheDeep

**Review by TheMonsterFromTheDeep — APPROVED** [review]
Looks good. I don't know if we need to use *all* the background colors in the demo file, but it doesn't really matter.

**Comment by CosmicWebServices** [comment]
There seems to be a conflict with another pr @rogersec I am trying to fix this now.

**Comment by CosmicWebServices** [comment]
Fixed merging now after travisci is done.

**Pull request merged**
