### PR TITLE
Implement 'strip' function

### PR DESCRIPTION
**Pull request by TheMonsterFromTheDeep**
Not entirely sure if this is exactly how we want this to work, but I've implemented a basic 'strip' function. If somebody wants to write tests or whatever that's fine

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
Hopefully, I did not break anything... seems to be working fine... prob will be duplicate files

**Comment by CosmicWebServices** [comment]
Whoops forgot we do not have python 3 support yet...

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep Do you mind if you make a new PR just to clean up the repo (without the travis stuff sense they are in master)... I kind of messed it up adding the Travis code?

**Comment by CosmicWebServices** [comment]
Ignore circleci

**Comment by TheMonsterFromTheDeep** [comment]
@CosmicWebServices what do you mean? What's unclean about the repo, currently?

**Comment by CosmicWebServices** [comment]
@TheMonsterFromTheDeep I made the travis ci changes in this repo and master... you know what I will just move this

**Comment by CosmicWebServices** [comment]
https://github.com/ilovecode1/Pyfancy-2/pull/19

**Pull request closed without merging**
